// Extendable.
var cityNamesMapping = {
	"Hyderabad": "Haydarabad",
	"Cracow": "Krakow",
	"Crakow": "Krakow",
	"Bakü (Bakı)": "Bakü",
	"Baku": "Bakü",
	"Oghuz": "Oguz",
	"London": "Greater London",
	"Londra": "Greater London",
	"Mingachevir": "Mingeçevir (Mingechaur)",
	"The Hague": "Den Haag (Lahey)",
	"Sumgayit": "Sumgayıt (Sumqayıt)",
	"Dubai": "Dubayy",
	"Dammam": "Ad Dammam",
	"Istanbul": "İstanbul",
	"Ihsangazi": "İhsangazi",
	"Ikizdere": "İkizdere",
	"Iliç": "İliç",
	"Imranlı": "İmranlı",
	"Imroz": "İmroz",
	"Incesu": "İncesu",
	"Incirliova": "İncirliova",
	"Inebolu": "İnebolu",
	"Inegöl": "İnegöl",
	"Iskenderun": "İskenderun",
	"Iskilip": "İskilip",
	"Ispir": "İspir",
	"Istanbul": "İstanbul",
	"Izmir": "İzmir",
	"Iznik": "İznik"
}