var countryNamesMapping = {
    "AFGHANISTAN": "Afganistan",
    "ALBANIA": "Arnavutluk",
    "ALGERIA": "Cezayir",
    "ANDORRA": "Andorra",
    "ANGOLA": "Angola",
    "ANGUILLA": "Anguilla",
    "ANTIGUA and Barbuda to": "Antigua ve barbuda",
    "ARGENTINA": "Arjantin",
    "ARMENIA": "Ermenistan",
    "ARUBA": "Aruba",
    "AUSTRALIA": "Avustralya",
    "AUSTRIA": "Avusturya",
    "AZERBAIJAN": "Azerbaycan",
    "AZERBAYCAN": "Azerbaycan",
    "AZERBAYJAN": "Azerbaycan",
    "AZERBEYCAN": "Azerbaycan",
    "BAHAMAS": "Bahamalar",
    "BAHRAIN": "Bahreyn",
    "BANGLADESH": "Banglades",
    "BANIN": "Benin",
    "BARBADOS": "Barbados",
    "BELARUS": "Belarus",
    "BELGIUM": "Belcika",
    "BELIZE": "Belize",
    "BERMUDA": "Bermuda",
    "BHUTAN": "Butan",
    "BOLIVIA": "Bolivya",
    "BOSNIA AND HERZEGOVINA": "Bosna hersek",
    "BOTSWANA": "Botsvana",
    "BRAZIL": "Brezilya",
    "BRUNEI": "Brunei",
    "BULGARIA": "Bulgaristan",
    "BURKINA FASO": "Burkina faso",
    "BURMA (MYANMAR)": "Burma (myanmar)",
    "BURUNDI": "Burundi",
    "CAMBODIA": "Kambocya",
    "CAMEROON": "Kamerun",
    "CANADA": "Kanada",
    "CAPE Verde": "Yesil burun",
    "CENTRAL AFRICAN REPUBLIC": "Orta afrika cumhuriyeti",
    "CHAD": "Çad",
    "CHECHNYA": "ÇeÇenistan",
    "CHINA": "Çin",
    "COLOMBIA": "Kolombiya",
    "COMOROS": "Komorlar",
    "COSTA RICA": "Kostarika",
    "COTE d'Ivoire": "Fildisi sahili",
    "CROATIA": "Hirvatistan",
    "CZECH Republic": "Cek cumhuriyeti",
    "DEMOCRATIC Republic of Congo": "Demokratik kongo cumhuriyeti",
    "DENMARK": "Danimarka",
    "DJIBOUTI": "Cibuti",
    "DOMINICAN REPUBLIC": "Dominik cumhuriyeti",
    "DOMINICAN": "Dominik",
    "EAST TIMOR": "Dogu timor",
    "ECUADOR": "Ekvator",
    "EGYPT": "Misir",
    "EL SALVADOR": "El salvador",
    "ENGLAND": "İngiltere",
    "EQUATORIAL Guinea": "Ekvator ginesi",
    "ERITREA": "Eritre",
    "ESTONIA": "Estonya",
    "ETHIOPIA": "Etyopya",
    "FIJI": "Fiji",
    "FINLAND": "Finlandiya",
    "FRANCE": "Fransa",
    "GABON": "Gabon",
    "GAMBIA": "Gambiya",
    "GB": "İngiltere",
    "GEORGIA": "Gürcistan",
    "GERMANY": "Almanya",
    "GHANA": "Gana",
    "GINA": "Gine",
    "GRANADA": "Granada",
    "GREAT BRITIAN": "İngiltere",
    "GREECE": "Yunanistan",
    "GREENLAND": "Gronland",
    "GUADELOP to": "Guadelope",
    "GUAM ISLAND": "Guam adasi",
    "GUATEMALA": "Guatemala",
    "GUYANE": "Guyana",
    "HAITI": "Haiti",
    "HONDURAS": "Honduras",
    "HONG KONG": "Hong kong",
    "HUNGARY": "Macaristan",
    "ICELAND": "İzlanda",
    "INDIA": "Hindistan",
    "INDONESIA": "Endonezya",
    "IRAN": "İran",
    "IRAQ": "Irak",
    "IRELAND": "İrlanda",
    "ISRAEL": "İsrail",
    "ITALY": "İtalya",
    "JAMAIK to": "Jamaika",
    "JAMAIKA": "Jamaika",
    "JAPAN": "Japonya",
    "JERUSALEM": "Kudus",
    "JORDAN": "Ürdün",
    "KAZAKHSTAN": "Kazakistan",
    "KENYA": "Kenya",
    "KOSOVO": "Kosova",
    "KUBA": "Kuba",
    "KUWAIT": "Kuveyt",
    "KYRGYZSTAN": "Kırgızistan",
    "LAOS": "Laos",
    "LATVIA": "Letonya",
    "LEBANON": "Lübnan",
    "LESOTHO": "Lesoto",
    "LIBERY in": "Liberya",
    "LIBYA": "Libya",
    "LITHUANIA": "Litvanya",
    "LUXEMBOURG": "Lüksemburg",
    "MACAU": "Makao",
    "MACEDONIA": "Makedonya",
    "MADAGASCAR": "Madagaskar",
    "MALAWI": "Malavi",
    "MALAYSIA": "Malezya",
    "MALDIVES": "Maldivler",
    "MALI": "Mali",
    "MALTA": "Malta",
    "MARTINIQUE": "Martinik",
    "MAURITANIA": "Moritanya",
    "MAURITIUS Island": "Mauritius adasi",
    "MAYOTTE": "Mayotte",
    "MEXICO": "Meksika",
    "MICRONESIA": "Mikronezya",
    "MOLDAVIA": "Moldavya",
    "MONACO": "Monako",
    "MONGOLIA": "Moğolistan",
    "MONTENEGRO": "Karadağ",
    "MONTSERRAT": "Montserrat (u.k.)",
    "MOROCCO": "Fas",
    "MOZAMBIQUE": "Mozambik",
    "NAMBA": "Nambiya",
    "NEPAL": "Nepal",
    "NETHERLANDS Antilles": "Hollanda antilleri",
    "NETHERLANDS": "Hollanda",
    "NEW CALEDONIA": "Yeni kaledonya",
    "NEW ZEALAND": "Yeni zellanda",
    "NICARAGUA": "Nikaragua",
    "NIGERIA": "Nijerya",
    "NIJAR": "Nijer",
    "NIUE": "Niue",
    "NORTH CYPRUS": "Kuzey Kıbrıs",
    "NORTH KOREA": "Kuzey Kore",
    "NORWAY": "Norvec",
    "OMAN": "Umman",
    "PAKISTAN": "Pakistan",
    "PALAU": "Palau",
    "PALESTINA": "Filistin",
    "PANAMA": "Panama",
    "PAPUA NEW Gina": "Papua yeni gine",
    "PARAGUAY": "Paraguay",
    "PERU": "Peru",
    "PHILIPPINES": "Filipinler",
    "PITCAIRN ISLAND": "Pitcairn adası",
    "POLISH": "Polonya",
    "POLAND": "Polonya",
    "PORTUGAL": "Portekiz",
    "PUERTO Rico": "Porto Riko",
    "QATAR": "Katar",
    "REUNION": "Reunion",
    "ROMANIA": "Romanya",
    "RUE Zealand": "Ruanda",
    "RUSSIA": "Rusya",
    "SAMOA": "Samoa",
    "SAUDI ARABIA": "S. arabistan",
    "SENEGAL": "Senegal",
    "SERBIA": "Sirbistan",
    "SEYCHELLES": "Seysel adalari",
    "SILI": "Şili",
    "SINGAPORE": "Singapur",
    "SLOVAKIA": "Slovakya",
    "SLOVENIA": "Slovenya",
    "SOMALIA": "Somali",
    "SOUTH AFRICA": "Güney afrika",
    "SOUTH KOREA": "Güney kore",
    "SPAIN": "İspanya",
    "SRI LANKA": "Sri lanka",
    "SUDAN": "Sudan",
    "SURINAME": "Surinam",
    "SVALBARD": "Svalbard",
    "SWAZILAND": "Svaziland",
    "SWEDEN": "İsveç",
    "SWITZERLAND": "İsviçre",
    "SYRIA": "Suriye",
    "TAIWAN": "Tayvan",
    "TAJIKISTAN": "Tacikistan",
    "TANZANIA": "Tanzanya",
    "THAILAND": "Tayland",
    "THE LIECHTENSTEIN": "Liechtenstein",
    "THE United Arab Emirate": "BAE",
    "THE UNITED ARAB EMIRATE": "BAE",
    "THE UNITED ARAB EMIRATES": "BAE",
    "UNITED ARAB EMIRATES": "BAE",
    "TOGO": "Togo",
    "TONGA": "Tonga",
    "TRINIDAT AND TOBAGO": "Trinidat ve tobago",
    "TUNISIA": "Tunus",
    "TURKEY": "Türkiye",
    "TURKMENISTAN": "Türkmenistan",
    "UGANDA": "Uganda",
    "UK": "İngiltere",
    "UKRAINE": "Ukrayna",
    "UKRAINE-Crimean": "Ukrayna-kırım",
    "UNITED KINGDOM": "İngiltere",
    "UNITED States": "ABD",
    "UNITED STATES": "ABD",
    "URUGUAY": "Uruguay",
    "USA": "ABD",
    "UZBEKISTAN": "Özbekistan",
    "VANUATU": "Vanuatu",
    "VATIKA the": "Vatikan",
    "VATIKAN": "Vatikan",
    "VENEZUELA": "Venezuela",
    "VIETNAM": "Vietnam",
    "YEMEN": "Yemen",
    "ZAMBIA": "Zambiya",
    "ZIMBABWE": "Zimbabve",
}