# Site settings
title: Bulunduğunuz yerde iftara ne kadar kaldı?
email: info@iftarvakitleri.org
description: > # iftar vakitleri, namaz vakitleri, sehirler, ankara, istanbul,
  iftar 2015, ramazan.
#baseurl: "/iftar" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "http://iftarvakitleri.org" # the base hostname & protocol for your site
#url: "https://hakanu.github.io"
twitter_username: orucbuddy
github_username:  hakanu

# Build settings
markdown: kramdown
