# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: ""
url: "http://iftarvakitleri.org" # the base hostname & protocol for your site
title: Okundu mu?
email: info@iftarvakitleri.org
author: Your Name
description: > # iftara ne kadar kaldı? Ezan ve namaz vakitleri, iftar vakitleri,
  namaz vakitleri, sehirler, ankara, istanbul, iftar 2015, ramazan,
  uluslararası namaz ve iftar zamanları.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
# permalink: pretty
permalink: "/:categories/:title"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/orucbuddy
  - title: facebook
    url: https://facebook.com/orucbuddy
  - title: mail
    url: mailto:info@iftarvakitleri.org

gems:
  - jekyll-sitemap